[tools]
rojo = { github = "rojo-rbx/rojo", version = "7.2.1" }
stylua = { github = "johnnymorganz/stylua", version = "0.16.1"}
selene = { github = "Kampfkarren/selene", version = "0.24.0"}
wally = { github = "UpliftGames/wally", version = "0.3.1" }
